### ISSUE TITLE
Value cannot be null

### ISSUE THREAD

**Issue by yotsubakoiwai** [unickq/allure-nunit#19]
hi,

when i ran my tests, they pass but the console writes down the following:
System.ArgumentNullException : Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Allure.Commons.Storage.AllureStorage.Get[T](String uuid)
   at Allure.Commons.AllureLifecycle.UpdateStep(Action`1 update)
   at Allure.Commons.AllureLifecycle.StopStep(Action`1 beforeStop)
   at NUnit.Allure.Core.AllureNUnitHelper.StopAll(Boolean isWrappedIntoStep)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\BeforeAndAfterTestCommand.cs:line 73

Did i miss anything with the setup? It's spitting our the allure-results (json files) and the html in allure-reports, but weird the nunit console is giving me that error???

**Comment by unickq** [comment]
@yotsubakoiwai 
 Can you show the code that raises this error? What steps you use, etc

**Comment by yotsubakoiwai** [comment]
Hi Nick, I tried doing it again and somehow fixed it by itself.. I removed the [AllureNUnit] tag from the test case and just use it in the BaseTest and it worked fine. Doesn't throw that error anymore. Thanks for looking into it :)

**Comment by FestTestQA** [comment]
Had same issue - a warning on dupe tag for derived classes would be usefull.
thanks

**Comment by unickq** [comment]
@FestTestQA 
I'm not sure that's possible to do through the code. Maybe I'm wrong - haven't used dotnet for a while, feel free to create PR with that

**Comment by oleg-finka** [comment]
Had same issue. It is really unclear from error message that I should remove [AllureNUnit] from fixture parent class...

**Comment by unickq** [comment]
@oleg-finka 

Yes, by default [AllureNUnit] attribute can be used only once. Because of  `ITestAction` implementation. I hid that error because of Allure.Instance, which tries to write already killed storage
