### ISSUE TITLE
NullReferenceException exception when running AllureNUnit

### ISSUE THREAD

**Issue by shaharw12** [unickq/allure-nunit#21]
Hi,

**I got the following stack trace:**
```
Test Name:	Test2
Test FullName:	TestClass7.Test2
Test Source:	C:\Sources\AllureTest\AllureTest\AllureTest\UnitTest1.cs : line 26
Test Outcome:	Failed
Test Duration:	0:00:00.001

Result StackTrace:	
at NUnit.Allure.Core.AllureNUnitHelper.GetTestProperties(String name)
   at NUnit.Allure.Core.AllureNUnitHelper.UpdateTestDataFromAttributes()
   at NUnit.Allure.Core.AllureNUnitHelper.StopTestCase()
   at NUnit.Allure.Core.AllureNUnitHelper.StopAll(Boolean isWrappedIntoStep)
   at NUnit.Allure.Core.AllureNUnitAttribute.AfterTest(ITest test)
   at NUnit.Framework.Internal.Commands.TestActionCommand.<>c__DisplayClass0_0.<.ctor>b__1(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__1()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.
```

**For the following code:**
```cs
using NUnit.Allure.Core;
using NUnit.Framework;

[AllureNUnit]
[TestFixture(Category = "asd")]
public class TestClass7
{
    [Test(Description = "test")]
    [Category("Debug")]
    public void Test1()
    {
        Assert.AreEqual(1, 1);
    }

    [Category("Debug")]
    [Test(Description = "test")]
    public void Test2()
    {
        Assert.AreEqual(2, 2);
    }
}
```

**I've installed the following NuGet in advance:**

- Microsoft.NET.Test.Sdk
- NUnit
- NUnit3TestAdapter
- NUnit.Allure

and used scoop to install allure using the following cmd command:
scoop install allure

May you please assist?

**Comment by unickq** [comment]
Thanks for pointing this issue.
Happens on newer NetFrameworks and NetCore3. 

Happened because of difference ITest types - **TestSuite** in old versions and **TestAssembly** in newer

Please try this fix.
https://www.nuget.org/packages/NUnit.Allure/1.0.6.1

**Comment by shaharw12** [comment]
@unickq Thanks!
The fix is working.

May you please elaborate more what was the issue ?

**Comment by unickq** [comment]
@shaharw12 

It's about different ITest types in old netframework and netcore3.
Look a commit changes
